image: python:3.11

stages:
  - test

before_script:
  - python --version
  - pip install -U pip
  - pip install django

test:
  stage: test
  script:
    # Basic syntax check
    - python -m compileall .

    # Django system check
    - python manage.py check

    # Ensure migrations are committed
    - python manage.py makemigrations --check --dry-run