# Generated by Django 6.0.1 on 2026-02-25 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the client company.', max_length=100, verbose_name='Company Name')),
                ('code', models.CharField(help_text="Unique identifier, e.g., 'HOSP01'.", max_length=20, unique=True, verbose_name='Company Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Client Company',
                'verbose_name_plural': 'Client Companies',
            },
        ),
        migrations.CreateModel(
            name='DietCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Diet Category Name')),
            ],
            options={
                'verbose_name_plural': 'Diet Categories',
            },
        ),
        migrations.CreateModel(
            name='ProcessedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(help_text="E.g., 'Peeled', 'Sliced'", max_length=50, verbose_name='Processing Method')),
                ('yield_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Format: 1.00 = 100%, 0.80 = 80%. Formula: Gross = Net / Yield', max_digits=5, verbose_name='Yield Rate')),
            ],
            options={
                'verbose_name': 'Processing Specification',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Material Name')),
                ('category', models.CharField(help_text='如: 冻品, 鲜品, 粮油, 调料', max_length=20, verbose_name='Category')),
                ('unit', models.CharField(default='kg', help_text='如: kg, {箱:10kg}, {袋:25kg}', max_length=50, verbose_name='Purchase Unit')),
                ('supplier', models.CharField(blank=True, default='', max_length=100, verbose_name='Supplier')),
                ('spec', models.CharField(blank=True, default='', max_length=100, verbose_name='Spec/Package')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Phone')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Dish Name')),
                ('allowed_diets', models.ManyToManyField(blank=True, to='core.dietcategory', verbose_name='Suitable for Diets')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_quantity', models.DecimalField(decimal_places=3, help_text='The weight AFTER processing (usually in kg or g).', max_digits=8, verbose_name='Net Qty per Serving')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.dish')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.processedmaterial', verbose_name='Ingredient (Net)')),
            ],
        ),
        migrations.AddField(
            model_name='processedmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.rawmaterial'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RW', 'Read/Write (Manager)'), ('RO', 'Read Only (Viewer)')], default='RO', max_length=2, verbose_name='Role Permission')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.clientcompany', verbose_name='Affiliated Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='processedmaterial',
            unique_together={('raw_material', 'method_name')},
        ),
        migrations.CreateModel(
            name='SupplierMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Unit Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Material',
                'unique_together': {('supplier', 'raw_material')},
            },
        ),
    ]
