# Generated by Django 6.0.1 on 2026-01-27 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Diet Category Name')),
            ],
            options={
                'verbose_name_plural': 'Diet Categories',
            },
        ),
        migrations.CreateModel(
            name='ProcessedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(help_text="E.g., 'Peeled', 'Sliced'", max_length=50, verbose_name='Processing Method')),
                ('yield_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Format: 1.00 = 100%, 0.80 = 80%. Formula: Gross = Net / Yield', max_digits=5, verbose_name='Yield Rate')),
            ],
            options={
                'verbose_name': 'Processing Specification',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Material Name')),
                ('category', models.CharField(choices=[('VEG', 'Vegetables'), ('MEAT', 'Meat/Poultry'), ('GRAIN', 'Grains'), ('COND', 'Condiments'), ('OTHER', 'Others')], max_length=10, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Unit Name')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Dish Name')),
                ('allowed_diets', models.ManyToManyField(blank=True, to='core.dietcategory', verbose_name='Suitable for Diets')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_quantity', models.DecimalField(decimal_places=3, help_text='The weight AFTER processing (usually in kg or g).', max_digits=8, verbose_name='Net Qty per Serving')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.dish')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.processedmaterial', verbose_name='Ingredient (Net)')),
            ],
        ),
        migrations.AddField(
            model_name='processedmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='default_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unit', verbose_name='Purchase Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='processedmaterial',
            unique_together={('raw_material', 'method_name')},
        ),
    ]
