# Generated by Django 6.0.1 on 2026-02-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dishingredient_raw_material_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.CharField(choices=[('鲜品', '鲜品'), ('冻品', '冻品')], max_length=20, verbose_name='Category'),
        ),
    ]
