# Generated by Django 6.0.1 on 2026-02-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materialcategory_rawmaterial_category_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='unit',
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='kg_per_unit',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='如: 1箱=10kg 则填 10', max_digits=10, verbose_name='每单位kg数'),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='unit_name',
            field=models.CharField(default='kg', help_text='如: 箱, 袋, 盒, kg', max_length=20, verbose_name='销售单位'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='suppliermaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价(每供应商单位)'),
        ),
    ]
