# Generated by Django 4.2.28 on 2026-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clientcompany_id_alter_dietcategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='spec',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Spec/Package'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Supplier'),
        ),
    ]
