# Generated by Django 6.0.1 on 2026-02-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_rawmaterial_spec_remove_rawmaterial_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_method',
            field=models.TextField(blank=True, default='', help_text='如: 先炒后炖，大火收汁', verbose_name='制作工艺'),
        ),
        migrations.AddField(
            model_name='dish',
            name='seasonings',
            field=models.TextField(blank=True, default='', help_text='如: 盐、酱油、料酒', verbose_name='调料'),
        ),
    ]
