# Generated by Django 4.2.28 on 2026-03-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dish_cooking_method_dish_seasonings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedmaterial',
            name='yield_rate',
        ),
        migrations.CreateModel(
            name='RawMaterialYieldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00 = 100%, 0.80 = 80%. Procurement gross = net / yield.', max_digits=5)),
                ('effective_date', models.DateField(help_text='Effective from this date (inclusive).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_rates', to='core.rawmaterial')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'unique_together': {('raw_material', 'effective_date')},
            },
        ),
    ]
