# Generated by Django 6.0.2 on 2026-03-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_processedmaterial_yield_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='当前库存量，单位 kg', max_digits=10, verbose_name='库存(kg)'),
        ),
    ]
