# Generated by Django 6.0.2 on 2026-03-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_stock_to_rawmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='上次收货确认时使用的供应商，下次生成采购单时自动预填', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='默认供应商'),
        ),
    ]
