# Generated by Django 6.0.1 on 2026-02-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompanyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Region Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany', verbose_name='Hospital/Company')),
            ],
            options={
                'verbose_name': 'Client Region / Ward',
                'verbose_name_plural': 'Client Regions',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='Delivery Date')),
                ('meal_time', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1, verbose_name='Meal Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'unique_together': {('company', 'target_date', 'meal_time')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Servings')),
                ('diet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dietcategory', verbose_name='Diet Type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.clientcompanyregion', verbose_name='Region')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.deliveryorder')),
            ],
            options={
                'verbose_name': 'Delivery Item',
            },
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='Processing Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
            ],
            options={
                'verbose_name': 'Processing Order',
            },
        ),
        migrations.CreateModel(
            name='ProcessingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Qty (kg)')),
                ('gross_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Qty (kg)')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish', verbose_name='Source Dish')),
                ('processed_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processedmaterial')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.processingorder')),
            ],
            options={
                'verbose_name': 'Processing Item',
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='For Usage Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Calculating)'), ('CONFIRMED', 'Confirmed (Sent)')], default='DRAFT', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gross_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qty (kg)')),
                ('notes', models.TextField(blank=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.procurementrequest')),
            ],
            options={
                'verbose_name': 'Procurement Line Item',
            },
        ),
        migrations.CreateModel(
            name='ReceivingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='Received Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivings', to='operations.procurementrequest')),
            ],
            options={
                'verbose_name': 'Receiving Record',
            },
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Qty')),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Qty')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.receivingrecord')),
            ],
            options={
                'verbose_name': 'Receiving Item',
            },
        ),
        migrations.CreateModel(
            name='DailyCensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Target Date')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Headcount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
                ('diet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dietcategory', verbose_name='Diet Type')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.clientcompanyregion', verbose_name='Region/Ward')),
            ],
            options={
                'verbose_name': 'Daily Census (Headcount)',
                'unique_together': {('company', 'date', 'region', 'diet_category')},
            },
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dietcategory')),
                ('dishes', models.ManyToManyField(blank=True, to='core.dish')),
            ],
            options={
                'unique_together': {('company', 'date', 'diet', 'meal_type')},
            },
        ),
        migrations.CreateModel(
            name='StapleDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1)),
                ('staple_type', models.CharField(choices=[('RICE', 'Rice'), ('NOODLE', 'Noodle')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Unit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dietcategory')),
            ],
            options={
                'unique_together': {('company', 'date', 'diet', 'meal_type', 'staple_type')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Day of Week')),
                ('meal_time', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1, verbose_name='Meal Period')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientcompany')),
                ('diet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dietcategory', verbose_name='Diet Set (e.g. Standard A)')),
                ('dishes', models.ManyToManyField(to='core.dish', verbose_name='Fixed Dishes')),
            ],
            options={
                'verbose_name': 'Weekly Menu Config',
                'verbose_name_plural': 'Weekly Menu Configs',
                'unique_together': {('company', 'diet_category', 'day_of_week', 'meal_time')},
            },
        ),
    ]
