# Generated by Django 6.0.1 on 2026-02-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='am_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='AM Qty (B+L)'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='pm_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PM Qty (D)'),
        ),
    ]
