# Generated by Django 6.0.1 on 2026-02-27 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_rawmaterial_spec_remove_rawmaterial_supplier_and_more'),
        ('operations', '0003_processingitem_nullable_processed_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价(每供应商单位)'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='supplier_unit_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='供应商单位'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='supplier_unit_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='供应商单位数量'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Calculating)'), ('PENDING', 'Pending Supplier Selection'), ('CONFIRMED', 'Confirmed (Sent)')], default='DRAFT', max_length=20),
        ),
    ]
