# Generated by Django 6.0.2 on 2026-03-02 18:20

import django.db.models.deletion
from django.db import migrations, models


def copy_m2m_data(apps, schema_editor):
    """Copy existing M2M data from the auto-generated through table to the new WeeklyMenuDish table."""
    WeeklyMenuDish = apps.get_model('operations', 'WeeklyMenuDish')
    # Read from the old auto-generated M2M table directly
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT weeklymenu_id, dish_id FROM operations_weeklymenu_dishes")
        rows = cursor.fetchall()
    for menu_id, dish_id in rows:
        WeeklyMenuDish.objects.using(db_alias).create(
            menu_id=menu_id, dish_id=dish_id, quantity=1
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dish_cooking_method_dish_seasonings'),
        ('operations', '0004_procurementitem_supplier_and_more'),
    ]

    operations = [
        # 1. Create the new through model table
        migrations.CreateModel(
            name='WeeklyMenuDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='该菜品在此餐次的数量（盘数），默认1', verbose_name='份数')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dishes', to='operations.weeklymenu')),
            ],
            options={
                'verbose_name': 'Weekly Menu Dish',
                'verbose_name_plural': 'Weekly Menu Dishes',
                'unique_together': {('menu', 'dish')},
            },
        ),
        # 2. Copy existing M2M data to the new through table
        migrations.RunPython(copy_m2m_data, migrations.RunPython.noop),
        # 3. Remove the old auto-generated M2M field
        migrations.RemoveField(
            model_name='weeklymenu',
            name='dishes',
        ),
        # 4. Re-add the M2M field with the explicit through model
        migrations.AddField(
            model_name='weeklymenu',
            name='dishes',
            field=models.ManyToManyField(through='operations.WeeklyMenuDish', to='core.dish', verbose_name='Fixed Dishes'),
        ),
    ]
