# Generated by Django 6.0.2 on 2026-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_weeklymenu_dish_through_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementitem',
            name='am_quantity',
        ),
        migrations.RemoveField(
            model_name='procurementitem',
            name='pm_quantity',
        ),
        migrations.RemoveField(
            model_name='procurementitem',
            name='supplier_unit_qty',
        ),
        migrations.RemoveField(
            model_name='procurementitem',
            name='total_gross_quantity',
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='demand_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='需求量(kg)'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='purchase_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='采购量(kg)'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存快照(kg)'),
        ),
        migrations.AddField(
            model_name='procurementitem',
            name='supplier_kg_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='用于 kg ↔ 供应商单位换算', max_digits=10, null=True, verbose_name='每单位kg数'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created (Generated)'), ('SUBMITTED', 'Submitted (Pending Receiving)'), ('CONFIRMED', 'Confirmed (Receiving Done)')], default='CREATED', max_length=20),
        ),
    ]
