# Generated by Django 4.2.28 on 2026-03-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_receivingrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingitem',
            name='meal_time',
            field=models.CharField(blank=True, choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1, null=True, verbose_name='Meal Time'),
        ),
    ]
